### ISSUE TITLE
WeightedAvgShift errors

### ISSUE THREAD

**Issue by pverspeelt** [ryanjgallagher/shifterator#29] opened 2021-11-08 17:48 UTC
When using the `WeightedAvgShift` with `handle_missing_scores` you get an error:

> UnboundLocalError: local variable 'lex_ref' referenced before assignment

reprex:

```
import shifterator as sh

text1 = {"A": 10, "B": 10, "C": 10, "D": 10, "E": 10, "F": 10, "G": 10}
text2 = {"B": 10, "C": 10, "D": 10, "E": 10, "F": 10, "G": 10, "H": 10}
weighted = sh.WeightedAvgShift(type2freq_1 = text1, 
                               type2freq_2 = text2, 
                               handle_missing_scores = "adopt") 

weighted = sh.WeightedAvgShift(type2freq_1 = text1, 
                               type2freq_2 = text2, 
                               handle_missing_scores = "exclude") 

```

**Comment by ryanjgallagher** [comment] 2021-11-08 19:03
I think this is somewhat expected behavior. The reason this is happening is because `type2score_1` and `type2score_2` are `None` because they haven't been passed to the `WeightedAvgShift`. But of course the `WeightedAvgShift` fails when there are no scores because scores are needed to do a weighted average.

I see though that I do try to catch that `None` case, which means at some point I decided it was OK if the generic WeightedAvgShift object wasn't passed scores https://github.com/ryanjgallagher/shifterator/blob/master/shifterator/shifterator.py#L80

Thanks for catching this inconsistency!

Should be closed by 9ce4cf761059a60d627ac85128563ddd55e59382 and 3d2fa5041355f4abe954d34af492cc23fb92dd8f together

**Closed as completed by ryanjgallagher** 2021-11-08 19:03 UTC
